### ISSUE TITLE
`has` falsely claims unregistered class-string is not known to container

### ISSUE THREAD

**Issue by jtojnar** [slince/di#10]
I am trying to use Symfony’s [`ContainerCommandLoader`](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Console/CommandLoader/ContainerCommandLoader.php) with this library but it does not list any commands unless I explicitly register them.

See the following minimal example:

```php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

class Foo {
}

$container = new Slince\Di\Container();

// $container->register(Foo::class);

var_dump($container->has(Foo::class));
var_dump($container->get(Foo::class));
```

which returns

```php
bool(false)
object(Foo)#9 (0) {
}
```

That is a violation of [section 1.1.2 Reading from a container](https://www.php-fig.org/psr/psr-11/#112-reading-from-a-container) of PSR-11 specification:

> If `has($id)` returns false, `get($id)` MUST throw a `NotFoundExceptionInterface`.

**Comment by slince** [comment]
fixed in 3.2.3
